<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTeamsStatsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('teams_stats', function (Blueprint $table) {
            $table->increments('player_id')->unsigned();
            $table->integer('gp_01')->default(0);
            $table->integer('w_01')->default(0);
            $table->integer('l_01')->default(0);
            $table->integer('o_01')->default(0);
            $table->integer('p_01')->default(0);
            $table->integer('f_01')->default(0);
            $table->integer('a_01')->default(0);
            $table->integer('gp_02')->default(0);
            $table->integer('w_02')->default(0);
            $table->integer('l_02')->default(0);
            $table->integer('o_02')->default(0);
            $table->integer('p_02')->default(0);
            $table->integer('f_02')->default(0);
            $table->integer('a_02')->default(0);
            $table->integer('gp_03')->default(0);
            $table->integer('w_03')->default(0);
            $table->integer('l_03')->default(0);
            $table->integer('o_03')->default(0);
            $table->integer('p_03')->default(0);
            $table->integer('f_03')->default(0);
            $table->integer('a_03')->default(0);
            $table->integer('gp_04')->default(0);
            $table->integer('w_04')->default(0);
            $table->integer('l_04')->default(0);
            $table->integer('o_04')->default(0);
            $table->integer('p_04')->default(0);
            $table->integer('f_04')->default(0);
            $table->integer('a_04')->default(0);
            $table->integer('gp_05')->default(0);
            $table->integer('w_05')->default(0);
            $table->integer('l_05')->default(0);
            $table->integer('o_05')->default(0);
            $table->integer('p_05')->default(0);
            $table->integer('f_05')->default(0);
            $table->integer('a_05')->default(0);
            $table->integer('gp_06')->default(0);
            $table->integer('w_06')->default(0);
            $table->integer('l_06')->default(0);
            $table->integer('o_06')->default(0);
            $table->integer('p_06')->default(0);
            $table->integer('f_06')->default(0);
            $table->integer('a_06')->default(0);
            $table->integer('gp_07')->default(0);
            $table->integer('w_07')->default(0);
            $table->integer('l_07')->default(0);
            $table->integer('o_07')->default(0);
            $table->integer('p_07')->default(0);
            $table->integer('f_07')->default(0);
            $table->integer('a_07')->default(0);
            $table->integer('gp_08')->default(0);
            $table->integer('w_08')->default(0);
            $table->integer('l_08')->default(0);
            $table->integer('o_08')->default(0);
            $table->integer('p_08')->default(0);
            $table->integer('f_08')->default(0);
            $table->integer('a_08')->default(0);
            $table->integer('gp_09')->default(0);
            $table->integer('w_09')->default(0);
            $table->integer('l_09')->default(0);
            $table->integer('o_09')->default(0);
            $table->integer('p_09')->default(0);
            $table->integer('f_09')->default(0);
            $table->integer('a_09')->default(0);
            $table->integer('gp_10')->default(0);
            $table->integer('w_10')->default(0);
            $table->integer('l_10')->default(0);
            $table->integer('o_10')->default(0);
            $table->integer('p_10')->default(0);
            $table->integer('f_10')->default(0);
            $table->integer('a_10')->default(0);
            $table->integer('gp_11')->default(0);
            $table->integer('w_11')->default(0);
            $table->integer('l_11')->default(0);
            $table->integer('o_11')->default(0);
            $table->integer('p_11')->default(0);
            $table->integer('f_11')->default(0);
            $table->integer('a_11')->default(0);
            $table->integer('gp_12')->default(0);
            $table->integer('w_12')->default(0);
            $table->integer('l_12')->default(0);
            $table->integer('o_12')->default(0);
            $table->integer('p_12')->default(0);
            $table->integer('f_12')->default(0);
            $table->integer('a_12')->default(0);
            $table->integer('gp_13')->default(0);
            $table->integer('w_13')->default(0);
            $table->integer('l_13')->default(0);
            $table->integer('o_13')->default(0);
            $table->integer('p_13')->default(0);
            $table->integer('f_13')->default(0);
            $table->integer('a_13')->default(0);
            $table->integer('gp_14')->default(0);
            $table->integer('w_14')->default(0);
            $table->integer('l_14')->default(0);
            $table->integer('o_14')->default(0);
            $table->integer('p_14')->default(0);
            $table->integer('f_14')->default(0);
            $table->integer('a_14')->default(0);
            $table->integer('gp_15')->default(0);
            $table->integer('w_15')->default(0);
            $table->integer('l_15')->default(0);
            $table->integer('o_15')->default(0);
            $table->integer('p_15')->default(0);
            $table->integer('f_15')->default(0);
            $table->integer('a_15')->default(0);
            $table->integer('gp_16')->default(0);
            $table->integer('w_16')->default(0);
            $table->integer('l_16')->default(0);
            $table->integer('o_16')->default(0);
            $table->integer('p_16')->default(0);
            $table->integer('f_16')->default(0);
            $table->integer('a_16')->default(0);
            $table->integer('gp_17')->default(0);
            $table->integer('w_17')->default(0);
            $table->integer('l_17')->default(0);
            $table->integer('o_17')->default(0);
            $table->integer('p_17')->default(0);
            $table->integer('f_17')->default(0);
            $table->integer('a_17')->default(0);
            $table->integer('gp_18')->default(0);
            $table->integer('w_18')->default(0);
            $table->integer('l_18')->default(0);
            $table->integer('o_18')->default(0);
            $table->integer('p_18')->default(0);
            $table->integer('f_18')->default(0);
            $table->integer('a_18')->default(0);
            $table->integer('gp_19')->default(0);
            $table->integer('w_19')->default(0);
            $table->integer('l_19')->default(0);
            $table->integer('o_19')->default(0);
            $table->integer('p_19')->default(0);
            $table->integer('f_19')->default(0);
            $table->integer('a_19')->default(0);
            $table->integer('gp_20')->default(0);
            $table->integer('w_20')->default(0);
            $table->integer('l_20')->default(0);
            $table->integer('o_20')->default(0);
            $table->integer('p_20')->default(0);
            $table->integer('f_20')->default(0);
            $table->integer('a_20')->default(0);
            $table->integer('gp_21')->default(0);
            $table->integer('w_21')->default(0);
            $table->integer('l_21')->default(0);
            $table->integer('o_21')->default(0);
            $table->integer('p_21')->default(0);
            $table->integer('f_21')->default(0);
            $table->integer('a_21')->default(0);
            $table->integer('gp_22')->default(0);
            $table->integer('w_22')->default(0);
            $table->integer('l_22')->default(0);
            $table->integer('o_22')->default(0);
            $table->integer('p_22')->default(0);
            $table->integer('f_22')->default(0);
            $table->integer('a_22')->default(0);

            $table->foreign('player_id')->references('id')->on('teams');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('teams_stats');
    }
}
