<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateSkatersStatsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('skaters_stats', function (Blueprint $table) {
            $table->increments('player_id')->unsigned();
            $table->integer('gp_01')->default(0);
            $table->integer('g_01')->default(0);
            $table->integer('a_01')->default(0);
            $table->integer('p_01')->default(0);
            $table->integer('h_01')->default(0);
            $table->integer('s_01')->default(0);
            $table->integer('f_01')->default(0);
            $table->integer('gp_02')->default(0);
            $table->integer('g_02')->default(0);
            $table->integer('a_02')->default(0);
            $table->integer('p_02')->default(0);
            $table->integer('h_02')->default(0);
            $table->integer('s_02')->default(0);
            $table->integer('f_02')->default(0);
            $table->integer('gp_03')->default(0);
            $table->integer('g_03')->default(0);
            $table->integer('a_03')->default(0);
            $table->integer('p_03')->default(0);
            $table->integer('h_03')->default(0);
            $table->integer('s_03')->default(0);
            $table->integer('f_03')->default(0);
            $table->integer('gp_04')->default(0);
            $table->integer('g_04')->default(0);
            $table->integer('a_04')->default(0);
            $table->integer('p_04')->default(0);
            $table->integer('h_04')->default(0);
            $table->integer('s_04')->default(0);
            $table->integer('f_04')->default(0);
            $table->integer('gp_05')->default(0);
            $table->integer('g_05')->default(0);
            $table->integer('a_05')->default(0);
            $table->integer('p_05')->default(0);
            $table->integer('h_05')->default(0);
            $table->integer('s_05')->default(0);
            $table->integer('f_05')->default(0);
            $table->integer('gp_06')->default(0);
            $table->integer('g_06')->default(0);
            $table->integer('a_06')->default(0);
            $table->integer('p_06')->default(0);
            $table->integer('h_06')->default(0);
            $table->integer('s_06')->default(0);
            $table->integer('f_06')->default(0);
            $table->integer('gp_07')->default(0);
            $table->integer('g_07')->default(0);
            $table->integer('a_07')->default(0);
            $table->integer('p_07')->default(0);
            $table->integer('h_07')->default(0);
            $table->integer('s_07')->default(0);
            $table->integer('f_07')->default(0);
            $table->integer('gp_08')->default(0);
            $table->integer('g_08')->default(0);
            $table->integer('a_08')->default(0);
            $table->integer('p_08')->default(0);
            $table->integer('h_08')->default(0);
            $table->integer('s_08')->default(0);
            $table->integer('f_08')->default(0);
            $table->integer('gp_09')->default(0);
            $table->integer('g_09')->default(0);
            $table->integer('a_09')->default(0);
            $table->integer('p_09')->default(0);
            $table->integer('h_09')->default(0);
            $table->integer('s_09')->default(0);
            $table->integer('f_09')->default(0);
            $table->integer('gp_10')->default(0);
            $table->integer('g_10')->default(0);
            $table->integer('a_10')->default(0);
            $table->integer('p_10')->default(0);
            $table->integer('h_10')->default(0);
            $table->integer('s_10')->default(0);
            $table->integer('f_10')->default(0);
            $table->integer('gp_11')->default(0);
            $table->integer('g_11')->default(0);
            $table->integer('a_11')->default(0);
            $table->integer('p_11')->default(0);
            $table->integer('h_11')->default(0);
            $table->integer('s_11')->default(0);
            $table->integer('f_11')->default(0);
            $table->integer('gp_12')->default(0);
            $table->integer('g_12')->default(0);
            $table->integer('a_12')->default(0);
            $table->integer('p_12')->default(0);
            $table->integer('h_12')->default(0);
            $table->integer('s_12')->default(0);
            $table->integer('f_12')->default(0);
            $table->integer('gp_13')->default(0);
            $table->integer('g_13')->default(0);
            $table->integer('a_13')->default(0);
            $table->integer('p_13')->default(0);
            $table->integer('h_13')->default(0);
            $table->integer('s_13')->default(0);
            $table->integer('f_13')->default(0);
            $table->integer('gp_14')->default(0);
            $table->integer('g_14')->default(0);
            $table->integer('a_14')->default(0);
            $table->integer('p_14')->default(0);
            $table->integer('h_14')->default(0);
            $table->integer('s_14')->default(0);
            $table->integer('f_14')->default(0);
            $table->integer('gp_15')->default(0);
            $table->integer('g_15')->default(0);
            $table->integer('a_15')->default(0);
            $table->integer('p_15')->default(0);
            $table->integer('h_15')->default(0);
            $table->integer('s_15')->default(0);
            $table->integer('f_15')->default(0);
            $table->integer('gp_16')->default(0);
            $table->integer('g_16')->default(0);
            $table->integer('a_16')->default(0);
            $table->integer('p_16')->default(0);
            $table->integer('h_16')->default(0);
            $table->integer('s_16')->default(0);
            $table->integer('f_16')->default(0);
            $table->integer('gp_17')->default(0);
            $table->integer('g_17')->default(0);
            $table->integer('a_17')->default(0);
            $table->integer('p_17')->default(0);
            $table->integer('h_17')->default(0);
            $table->integer('s_17')->default(0);
            $table->integer('f_17')->default(0);
            $table->integer('gp_18')->default(0);
            $table->integer('g_18')->default(0);
            $table->integer('a_18')->default(0);
            $table->integer('p_18')->default(0);
            $table->integer('h_18')->default(0);
            $table->integer('s_18')->default(0);
            $table->integer('f_18')->default(0);
            $table->integer('gp_19')->default(0);
            $table->integer('g_19')->default(0);
            $table->integer('a_19')->default(0);
            $table->integer('p_19')->default(0);
            $table->integer('h_19')->default(0);
            $table->integer('s_19')->default(0);
            $table->integer('f_19')->default(0);
            $table->integer('gp_20')->default(0);
            $table->integer('g_20')->default(0);
            $table->integer('a_20')->default(0);
            $table->integer('p_20')->default(0);
            $table->integer('h_20')->default(0);
            $table->integer('s_20')->default(0);
            $table->integer('f_20')->default(0);
            $table->integer('gp_21')->default(0);
            $table->integer('g_21')->default(0);
            $table->integer('a_21')->default(0);
            $table->integer('p_21')->default(0);
            $table->integer('h_21')->default(0);
            $table->integer('s_21')->default(0);
            $table->integer('f_21')->default(0);
            $table->integer('gp_22')->default(0);
            $table->integer('g_22')->default(0);
            $table->integer('a_22')->default(0);
            $table->integer('p_22')->default(0);
            $table->integer('h_22')->default(0);
            $table->integer('s_22')->default(0);
            $table->integer('f_22')->default(0);

            $table->foreign('player_id')->references('id')->on('skaters');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('skaters_stats');
    }
}
