<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateGoaliesStatsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('goalies_stats', function (Blueprint $table) {
            $table->increments('player_id')->unsigned();
            $table->integer('gp_01')->default(0);
            $table->integer('w_01')->default(0);
            $table->integer('l_01')->default(0);
            $table->integer('o_01')->default(0);
            $table->integer('g_01')->default(0);
            $table->integer('s_01')->default(0);
            $table->integer('i_01')->default(0);
            $table->integer('gp_02')->default(0);
            $table->integer('w_02')->default(0);
            $table->integer('l_02')->default(0);
            $table->integer('o_02')->default(0);
            $table->integer('g_02')->default(0);
            $table->integer('s_02')->default(0);
            $table->integer('i_02')->default(0);
            $table->integer('gp_03')->default(0);
            $table->integer('w_03')->default(0);
            $table->integer('l_03')->default(0);
            $table->integer('o_03')->default(0);
            $table->integer('g_03')->default(0);
            $table->integer('s_03')->default(0);
            $table->integer('i_03')->default(0);
            $table->integer('gp_04')->default(0);
            $table->integer('w_04')->default(0);
            $table->integer('l_04')->default(0);
            $table->integer('o_04')->default(0);
            $table->integer('g_04')->default(0);
            $table->integer('s_04')->default(0);
            $table->integer('i_04')->default(0);
            $table->integer('gp_05')->default(0);
            $table->integer('w_05')->default(0);
            $table->integer('l_05')->default(0);
            $table->integer('o_05')->default(0);
            $table->integer('g_05')->default(0);
            $table->integer('s_05')->default(0);
            $table->integer('i_05')->default(0);
            $table->integer('gp_06')->default(0);
            $table->integer('w_06')->default(0);
            $table->integer('l_06')->default(0);
            $table->integer('o_06')->default(0);
            $table->integer('g_06')->default(0);
            $table->integer('s_06')->default(0);
            $table->integer('i_06')->default(0);
            $table->integer('gp_07')->default(0);
            $table->integer('w_07')->default(0);
            $table->integer('l_07')->default(0);
            $table->integer('o_07')->default(0);
            $table->integer('g_07')->default(0);
            $table->integer('s_07')->default(0);
            $table->integer('i_07')->default(0);
            $table->integer('gp_08')->default(0);
            $table->integer('w_08')->default(0);
            $table->integer('l_08')->default(0);
            $table->integer('o_08')->default(0);
            $table->integer('g_08')->default(0);
            $table->integer('s_08')->default(0);
            $table->integer('i_08')->default(0);
            $table->integer('gp_09')->default(0);
            $table->integer('w_09')->default(0);
            $table->integer('l_09')->default(0);
            $table->integer('o_09')->default(0);
            $table->integer('g_09')->default(0);
            $table->integer('s_09')->default(0);
            $table->integer('i_09')->default(0);
            $table->integer('gp_10')->default(0);
            $table->integer('w_10')->default(0);
            $table->integer('l_10')->default(0);
            $table->integer('o_10')->default(0);
            $table->integer('g_10')->default(0);
            $table->integer('s_10')->default(0);
            $table->integer('i_10')->default(0);
            $table->integer('gp_11')->default(0);
            $table->integer('w_11')->default(0);
            $table->integer('l_11')->default(0);
            $table->integer('o_11')->default(0);
            $table->integer('g_11')->default(0);
            $table->integer('s_11')->default(0);
            $table->integer('i_11')->default(0);
            $table->integer('gp_12')->default(0);
            $table->integer('w_12')->default(0);
            $table->integer('l_12')->default(0);
            $table->integer('o_12')->default(0);
            $table->integer('g_12')->default(0);
            $table->integer('s_12')->default(0);
            $table->integer('i_12')->default(0);
            $table->integer('gp_13')->default(0);
            $table->integer('w_13')->default(0);
            $table->integer('l_13')->default(0);
            $table->integer('o_13')->default(0);
            $table->integer('g_13')->default(0);
            $table->integer('s_13')->default(0);
            $table->integer('i_13')->default(0);
            $table->integer('gp_14')->default(0);
            $table->integer('w_14')->default(0);
            $table->integer('l_14')->default(0);
            $table->integer('o_14')->default(0);
            $table->integer('g_14')->default(0);
            $table->integer('s_14')->default(0);
            $table->integer('i_14')->default(0);
            $table->integer('gp_15')->default(0);
            $table->integer('w_15')->default(0);
            $table->integer('l_15')->default(0);
            $table->integer('o_15')->default(0);
            $table->integer('g_15')->default(0);
            $table->integer('s_15')->default(0);
            $table->integer('i_15')->default(0);
            $table->integer('gp_16')->default(0);
            $table->integer('w_16')->default(0);
            $table->integer('l_16')->default(0);
            $table->integer('o_16')->default(0);
            $table->integer('g_16')->default(0);
            $table->integer('s_16')->default(0);
            $table->integer('i_16')->default(0);
            $table->integer('gp_17')->default(0);
            $table->integer('w_17')->default(0);
            $table->integer('l_17')->default(0);
            $table->integer('o_17')->default(0);
            $table->integer('g_17')->default(0);
            $table->integer('s_17')->default(0);
            $table->integer('i_17')->default(0);
            $table->integer('gp_18')->default(0);
            $table->integer('w_18')->default(0);
            $table->integer('l_18')->default(0);
            $table->integer('o_18')->default(0);
            $table->integer('g_18')->default(0);
            $table->integer('s_18')->default(0);
            $table->integer('i_18')->default(0);
            $table->integer('gp_19')->default(0);
            $table->integer('w_19')->default(0);
            $table->integer('l_19')->default(0);
            $table->integer('o_19')->default(0);
            $table->integer('g_19')->default(0);
            $table->integer('s_19')->default(0);
            $table->integer('i_19')->default(0);
            $table->integer('gp_20')->default(0);
            $table->integer('w_20')->default(0);
            $table->integer('l_20')->default(0);
            $table->integer('o_20')->default(0);
            $table->integer('g_20')->default(0);
            $table->integer('s_20')->default(0);
            $table->integer('i_20')->default(0);
            $table->integer('gp_21')->default(0);
            $table->integer('w_21')->default(0);
            $table->integer('l_21')->default(0);
            $table->integer('o_21')->default(0);
            $table->integer('g_21')->default(0);
            $table->integer('s_21')->default(0);
            $table->integer('i_21')->default(0);
            $table->integer('gp_22')->default(0);
            $table->integer('w_22')->default(0);
            $table->integer('l_22')->default(0);
            $table->integer('o_22')->default(0);
            $table->integer('g_22')->default(0);
            $table->integer('s_22')->default(0);
            $table->integer('i_22')->default(0);

            $table->foreign('player_id')->references('id')->on('skaters');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('goalies_stats');
    }
}
