<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Models\Standing;
use App\Repositories\FranchiseRepository;
use App\Repositories\VariableRepository;
use App\Repositories\StandingRepository;

class StandingController extends Controller
{
    protected $franchise;
    protected $variable;
    protected $standing;

    public function __construct(FranchiseRepository $franchise, VariableRepository $variable, StandingRepository $standing )
    {
        $this->franchise = $franchise;
        $this->variable = $variable;
        $this->standing = $standing;
    }

    public function standing(Request $request)
    {
        return view('standing', [

            'week_current' => $this->variable->weekCurrent(),
            'total_top' => $this->standing->topTotal(),
            'skater_top' => $this->standing->topSkater(),
            'goalie_top' => $this->standing->topGoalie(),
            'team_top' => $this->standing->topTeam(),

            'franchise_1' => $this->franchise->id(1),
            'rank_1' => $this->standing->rank(1),
            'points_back_1' => $this->standing->pointsBack(1),
            'best_1' => $this->standing->bestWeekly(1),
            'worst_1' => $this->standing->worstWeekly(1),
            'average_1' => $this->standing->averageWeekly(1),
            'total_1' => $this->standing->total(1),
            'skater_1' => $this->standing->skater(1),
            'goalie_1' => $this->standing->goalie(1),
            'team_1' => $this->standing->team(1),
            'w01_1' => $this->standing->weekly(1, 'w_01'),
            'w02_1' => $this->standing->weekly(1, 'w_02'),
            'w03_1' => $this->standing->weekly(1, 'w_03'),
            'w04_1' => $this->standing->weekly(1, 'w_04'),
            'w05_1' => $this->standing->weekly(1, 'w_05'),
            'w06_1' => $this->standing->weekly(1, 'w_06'),
            'w07_1' => $this->standing->weekly(1, 'w_07'),
            'w08_1' => $this->standing->weekly(1, 'w_08'),
            'w09_1' => $this->standing->weekly(1, 'w_09'),
            'w10_1' => $this->standing->weekly(1, 'w_10'),
            'w11_1' => $this->standing->weekly(1, 'w_11'),
            'w12_1' => $this->standing->weekly(1, 'w_12'),
            'w13_1' => $this->standing->weekly(1, 'w_13'),
            'w14_1' => $this->standing->weekly(1, 'w_14'),
            'w15_1' => $this->standing->weekly(1, 'w_15'),
            'w16_1' => $this->standing->weekly(1, 'w_16'),
            'w17_1' => $this->standing->weekly(1, 'w_17'),
            'w18_1' => $this->standing->weekly(1, 'w_18'),
            'w19_1' => $this->standing->weekly(1, 'w_19'),
            'w20_1' => $this->standing->weekly(1, 'w_20'),
            'w21_1' => $this->standing->weekly(1, 'w_21'),
            'w22_1' => $this->standing->weekly(1, 'w_22'),

            'franchise_2' => $this->franchise->id(2),
            'rank_2' => $this->standing->rank(2),
            'points_back_2' => $this->standing->pointsBack(2),
            'best_2' => $this->standing->bestWeekly(2),
            'worst_2' => $this->standing->worstWeekly(2),
            'average_2' => $this->standing->averageWeekly(2),
            'total_2' => $this->standing->total(2),
            'skater_2' => $this->standing->skater(2),
            'goalie_2' => $this->standing->goalie(2),
            'team_2' => $this->standing->team(2),
            'w01_2' => $this->standing->weekly(2, 'w_01'),
            'w02_2' => $this->standing->weekly(2, 'w_02'),
            'w03_2' => $this->standing->weekly(2, 'w_03'),
            'w04_2' => $this->standing->weekly(2, 'w_04'),
            'w05_2' => $this->standing->weekly(2, 'w_05'),
            'w06_2' => $this->standing->weekly(2, 'w_06'),
            'w07_2' => $this->standing->weekly(2, 'w_07'),
            'w08_2' => $this->standing->weekly(2, 'w_08'),
            'w09_2' => $this->standing->weekly(2, 'w_09'),
            'w10_2' => $this->standing->weekly(2, 'w_10'),
            'w11_2' => $this->standing->weekly(2, 'w_11'),
            'w12_2' => $this->standing->weekly(2, 'w_12'),
            'w13_2' => $this->standing->weekly(2, 'w_13'),
            'w14_2' => $this->standing->weekly(2, 'w_14'),
            'w15_2' => $this->standing->weekly(2, 'w_15'),
            'w16_2' => $this->standing->weekly(2, 'w_16'),
            'w17_2' => $this->standing->weekly(2, 'w_17'),
            'w18_2' => $this->standing->weekly(2, 'w_18'),
            'w19_2' => $this->standing->weekly(2, 'w_19'),
            'w20_2' => $this->standing->weekly(2, 'w_20'),
            'w21_2' => $this->standing->weekly(2, 'w_21'),
            'w22_2' => $this->standing->weekly(2, 'w_22'),

            'franchise_3' => $this->franchise->id(3),
            'rank_3' => $this->standing->rank(3),
            'points_back_3' => $this->standing->pointsBack(3),
            'best_3' => $this->standing->bestWeekly(3),
            'worst_3' => $this->standing->worstWeekly(3),
            'average_3' => $this->standing->averageWeekly(3),
            'total_3' => $this->standing->total(3),
            'skater_3' => $this->standing->skater(3),
            'goalie_3' => $this->standing->goalie(3),
            'team_3' => $this->standing->team(3),
            'w01_3' => $this->standing->weekly(3, 'w_01'),
            'w02_3' => $this->standing->weekly(3, 'w_02'),
            'w03_3' => $this->standing->weekly(3, 'w_03'),
            'w04_3' => $this->standing->weekly(3, 'w_04'),
            'w05_3' => $this->standing->weekly(3, 'w_05'),
            'w06_3' => $this->standing->weekly(3, 'w_06'),
            'w07_3' => $this->standing->weekly(3, 'w_07'),
            'w08_3' => $this->standing->weekly(3, 'w_08'),
            'w09_3' => $this->standing->weekly(3, 'w_09'),
            'w10_3' => $this->standing->weekly(3, 'w_10'),
            'w11_3' => $this->standing->weekly(3, 'w_11'),
            'w12_3' => $this->standing->weekly(3, 'w_12'),
            'w13_3' => $this->standing->weekly(3, 'w_13'),
            'w14_3' => $this->standing->weekly(3, 'w_14'),
            'w15_3' => $this->standing->weekly(3, 'w_15'),
            'w16_3' => $this->standing->weekly(3, 'w_16'),
            'w17_3' => $this->standing->weekly(3, 'w_17'),
            'w18_3' => $this->standing->weekly(3, 'w_18'),
            'w19_3' => $this->standing->weekly(3, 'w_19'),
            'w20_3' => $this->standing->weekly(3, 'w_20'),
            'w21_3' => $this->standing->weekly(3, 'w_21'),
            'w22_3' => $this->standing->weekly(3, 'w_22'),

            'franchise_4' => $this->franchise->id(4),
            'rank_4' => $this->standing->rank(4),
            'points_back_4' => $this->standing->pointsBack(4),
            'best_4' => $this->standing->bestWeekly(4),
            'worst_4' => $this->standing->worstWeekly(4),
            'average_4' => $this->standing->averageWeekly(4),
            'total_4' => $this->standing->total(4),
            'skater_4' => $this->standing->skater(4),
            'goalie_4' => $this->standing->goalie(4),
            'team_4' => $this->standing->team(4),
            'w01_4' => $this->standing->weekly(4, 'w_01'),
            'w02_4' => $this->standing->weekly(4, 'w_02'),
            'w03_4' => $this->standing->weekly(4, 'w_03'),
            'w04_4' => $this->standing->weekly(4, 'w_04'),
            'w05_4' => $this->standing->weekly(4, 'w_05'),
            'w06_4' => $this->standing->weekly(4, 'w_06'),
            'w07_4' => $this->standing->weekly(4, 'w_07'),
            'w08_4' => $this->standing->weekly(4, 'w_08'),
            'w09_4' => $this->standing->weekly(4, 'w_09'),
            'w10_4' => $this->standing->weekly(4, 'w_10'),
            'w11_4' => $this->standing->weekly(4, 'w_11'),
            'w12_4' => $this->standing->weekly(4, 'w_12'),
            'w13_4' => $this->standing->weekly(4, 'w_13'),
            'w14_4' => $this->standing->weekly(4, 'w_14'),
            'w15_4' => $this->standing->weekly(4, 'w_15'),
            'w16_4' => $this->standing->weekly(4, 'w_16'),
            'w17_4' => $this->standing->weekly(4, 'w_17'),
            'w18_4' => $this->standing->weekly(4, 'w_18'),
            'w19_4' => $this->standing->weekly(4, 'w_19'),
            'w20_4' => $this->standing->weekly(4, 'w_20'),
            'w21_4' => $this->standing->weekly(4, 'w_21'),
            'w22_4' => $this->standing->weekly(4, 'w_22'),

            'franchise_5' => $this->franchise->id(5),
            'rank_5' => $this->standing->rank(5),
            'points_back_5' => $this->standing->pointsBack(5),
            'best_5' => $this->standing->bestWeekly(5),
            'worst_5' => $this->standing->worstWeekly(5),
            'average_5' => $this->standing->averageWeekly(5),
            'total_5' => $this->standing->total(5),
            'skater_5' => $this->standing->skater(5),
            'goalie_5' => $this->standing->goalie(5),
            'team_5' => $this->standing->team(5),
            'w01_5' => $this->standing->weekly(5, 'w_01'),
            'w02_5' => $this->standing->weekly(5, 'w_02'),
            'w03_5' => $this->standing->weekly(5, 'w_03'),
            'w04_5' => $this->standing->weekly(5, 'w_04'),
            'w05_5' => $this->standing->weekly(5, 'w_05'),
            'w06_5' => $this->standing->weekly(5, 'w_06'),
            'w07_5' => $this->standing->weekly(5, 'w_07'),
            'w08_5' => $this->standing->weekly(5, 'w_08'),
            'w09_5' => $this->standing->weekly(5, 'w_09'),
            'w10_5' => $this->standing->weekly(5, 'w_10'),
            'w11_5' => $this->standing->weekly(5, 'w_11'),
            'w12_5' => $this->standing->weekly(5, 'w_12'),
            'w13_5' => $this->standing->weekly(5, 'w_13'),
            'w14_5' => $this->standing->weekly(5, 'w_14'),
            'w15_5' => $this->standing->weekly(5, 'w_15'),
            'w16_5' => $this->standing->weekly(5, 'w_16'),
            'w17_5' => $this->standing->weekly(5, 'w_17'),
            'w18_5' => $this->standing->weekly(5, 'w_18'),
            'w19_5' => $this->standing->weekly(5, 'w_19'),
            'w20_5' => $this->standing->weekly(5, 'w_20'),
            'w21_5' => $this->standing->weekly(5, 'w_21'),
            'w22_5' => $this->standing->weekly(5, 'w_22'),

            'franchise_6' => $this->franchise->id(6),
            'rank_6' => $this->standing->rank(6),
            'points_back_6' => $this->standing->pointsBack(6),
            'best_6' => $this->standing->bestWeekly(6),
            'worst_6' => $this->standing->worstWeekly(6),
            'average_6' => $this->standing->averageWeekly(6),
            'total_6' => $this->standing->total(6),
            'skater_6' => $this->standing->skater(6),
            'goalie_6' => $this->standing->goalie(6),
            'team_6' => $this->standing->team(6),
            'w01_6' => $this->standing->weekly(6, 'w_01'),
            'w02_6' => $this->standing->weekly(6, 'w_02'),
            'w03_6' => $this->standing->weekly(6, 'w_03'),
            'w04_6' => $this->standing->weekly(6, 'w_04'),
            'w05_6' => $this->standing->weekly(6, 'w_05'),
            'w06_6' => $this->standing->weekly(6, 'w_06'),
            'w07_6' => $this->standing->weekly(6, 'w_07'),
            'w08_6' => $this->standing->weekly(6, 'w_08'),
            'w09_6' => $this->standing->weekly(6, 'w_09'),
            'w10_6' => $this->standing->weekly(6, 'w_10'),
            'w11_6' => $this->standing->weekly(6, 'w_11'),
            'w12_6' => $this->standing->weekly(6, 'w_12'),
            'w13_6' => $this->standing->weekly(6, 'w_13'),
            'w14_6' => $this->standing->weekly(6, 'w_14'),
            'w15_6' => $this->standing->weekly(6, 'w_15'),
            'w16_6' => $this->standing->weekly(6, 'w_16'),
            'w17_6' => $this->standing->weekly(6, 'w_17'),
            'w18_6' => $this->standing->weekly(6, 'w_18'),
            'w19_6' => $this->standing->weekly(6, 'w_19'),
            'w20_6' => $this->standing->weekly(6, 'w_20'),
            'w21_6' => $this->standing->weekly(6, 'w_21'),
            'w22_6' => $this->standing->weekly(6, 'w_22'),

            'franchise_7' => $this->franchise->id(7),
            'rank_7' => $this->standing->rank(7),
            'points_back_7' => $this->standing->pointsBack(7),
            'best_7' => $this->standing->bestWeekly(7),
            'worst_7' => $this->standing->worstWeekly(7),
            'average_7' => $this->standing->averageWeekly(7),
            'total_7' => $this->standing->total(7),
            'skater_7' => $this->standing->skater(7),
            'goalie_7' => $this->standing->goalie(7),
            'team_7' => $this->standing->team(7),
            'w01_7' => $this->standing->weekly(7, 'w_01'),
            'w02_7' => $this->standing->weekly(7, 'w_02'),
            'w03_7' => $this->standing->weekly(7, 'w_03'),
            'w04_7' => $this->standing->weekly(7, 'w_04'),
            'w05_7' => $this->standing->weekly(7, 'w_05'),
            'w06_7' => $this->standing->weekly(7, 'w_06'),
            'w07_7' => $this->standing->weekly(7, 'w_07'),
            'w08_7' => $this->standing->weekly(7, 'w_08'),
            'w09_7' => $this->standing->weekly(7, 'w_09'),
            'w10_7' => $this->standing->weekly(7, 'w_10'),
            'w11_7' => $this->standing->weekly(7, 'w_11'),
            'w12_7' => $this->standing->weekly(7, 'w_12'),
            'w13_7' => $this->standing->weekly(7, 'w_13'),
            'w14_7' => $this->standing->weekly(7, 'w_14'),
            'w15_7' => $this->standing->weekly(7, 'w_15'),
            'w16_7' => $this->standing->weekly(7, 'w_16'),
            'w17_7' => $this->standing->weekly(7, 'w_17'),
            'w18_7' => $this->standing->weekly(7, 'w_18'),
            'w19_7' => $this->standing->weekly(7, 'w_19'),
            'w20_7' => $this->standing->weekly(7, 'w_20'),
            'w21_7' => $this->standing->weekly(7, 'w_21'),
            'w22_7' => $this->standing->weekly(7, 'w_22'),

            'franchise_8' => $this->franchise->id(8),
            'rank_8' => $this->standing->rank(8),
            'points_back_8' => $this->standing->pointsBack(8),
            'best_8' => $this->standing->bestWeekly(8),
            'worst_8' => $this->standing->worstWeekly(8),
            'average_8' => $this->standing->averageWeekly(8),
            'total_8' => $this->standing->total(8),
            'skater_8' => $this->standing->skater(8),
            'goalie_8' => $this->standing->goalie(8),
            'team_8' => $this->standing->team(8),
            'w01_8' => $this->standing->weekly(8, 'w_01'),
            'w02_8' => $this->standing->weekly(8, 'w_02'),
            'w03_8' => $this->standing->weekly(8, 'w_03'),
            'w04_8' => $this->standing->weekly(8, 'w_04'),
            'w05_8' => $this->standing->weekly(8, 'w_05'),
            'w06_8' => $this->standing->weekly(8, 'w_06'),
            'w07_8' => $this->standing->weekly(8, 'w_07'),
            'w08_8' => $this->standing->weekly(8, 'w_08'),
            'w09_8' => $this->standing->weekly(8, 'w_09'),
            'w10_8' => $this->standing->weekly(8, 'w_10'),
            'w11_8' => $this->standing->weekly(8, 'w_11'),
            'w12_8' => $this->standing->weekly(8, 'w_12'),
            'w13_8' => $this->standing->weekly(8, 'w_13'),
            'w14_8' => $this->standing->weekly(8, 'w_14'),
            'w15_8' => $this->standing->weekly(8, 'w_15'),
            'w16_8' => $this->standing->weekly(8, 'w_16'),
            'w17_8' => $this->standing->weekly(8, 'w_17'),
            'w18_8' => $this->standing->weekly(8, 'w_18'),
            'w19_8' => $this->standing->weekly(8, 'w_19'),
            'w20_8' => $this->standing->weekly(8, 'w_20'),
            'w21_8' => $this->standing->weekly(8, 'w_21'),
            'w22_8' => $this->standing->weekly(8, 'w_22'),
        ]);
    }
}
